version: "2"

services:
    apigateway:
        build: ./Gateway/app/
        ports:
            - "5000:5000"
        environment:
            - AZURE_SERVICE_BUS_NAMESPACE=dummynamespace
            - AZURE_SERVICE_BUS_POLICY=dummypolicy
            - AZURE_SERVICE_BUS_KEY=dummykey
            - AZURE_SERVICE_BUS_QUEUE=dummyqueue
            - USERS_SERVICE=users
            - BIKES_SERVICE=bikes
            - RESERVATIONS_SERVICE=reservations
            - BILLING_SERVICE=billing
        links:
            - bikes
            - users
            - billing
            - reservations
        depends_on:
            - bikes
            - reservationengine
            - users
            - billing
            - reservations

    devsite:
        build: ./DevSite/
        environment:
            - GATEWAY_SERVICE_URI=http://apigateway:5000
        links:
            - apigateway
        depends_on:
            - apigateway
        ports:
            - "8080:80"

    bikes:
        build: ./Bikes/
        environment:
            - MONGO_DB_CONNECTION_STRING=mongodb://mongo
            - MONGO_DB_COLLECTION=bikes
        depends_on:
            - mongo
        links:
            - mongo
        ports:
            - "8081:80"

    users:
        build: ./Users/app/
        ports:
            - "8082:80"
        environment:
            - USER_SQLDB_USERNAME=dummyuser
            - USER_SQLDB_PASSWORD=dummypassword
            - USER_SQLDB_SERVER=dummyserver
            - USER_SQLDB_DATABASE=dummydb

    billing:
        build: ./Billing/
        ports:
            - "8083:8080"
        environment:
            - MONGODB_CONNECTION_STRING=mongodb://mongo
            - MONGODB_DBNAME=billing
        depends_on:
            - mongo
        links:
            - mongo

    reservations:
        build: ./Reservation/app/
        ports:
            - "8084:80"
        environment:
            - RESERVATION_MONGODB_CONNECTION_STRING=mongodb://mongo
            - RESERVATION_MONGODB_DATABASE=resdb
            - RESERVATION_MONGODB_COLLECTION=reservation
        depends_on:
            - mongo
        links:
            - mongo

    reservationengine:
        build: ./ReservationEngine/app/
        environment:
            - AZURE_SERVICE_BUS_NAMESPACE=dummynamespace
            - AZURE_SERVICE_BUS_POLICY=dummypolicy
            - AZURE_SERVICE_BUS_KEY=dummykey
            - AZURE_SERVICE_BUS_QUEUE=dummyqueue
            - RESERVATION_MONGODB_CONNECTION_STRING=mongodb://mongo
            - RESERVATION_MONGODB_DATABASE=resdb
            - RESERVATION_MONGODB_COLLECTION=reservation
            - BIKES_SERVICE=bikes
            - BILLING_SERVICE=billing
        depends_on:
            - bikes
            - mongo
            - notification
            - billing
            - reservations
        links:
            - bikes
            - mongo
            - reservations
            - billing
            - notification

    notification:
        build: ./Notification/
        environment:
            - OUT_AMQP_URI=amqp://rabbit
            - IN_AMQP_URI=amqp://rabbit
            - OUT_EXCHANGE=out
            - IN_EXCHANGE=in
            - IN_BINDINGKEY=
            - CONSUMERTAG_OVERRIDE=
        depends_on:
            - rabbit
        links:
            - rabbit

    mongo:
        image: mongo:3.4
        expose:
            - "27017"
        ports:
            - "27017:27017"

    rabbit:
        image: rabbitmq:3-management
        expose:
            - "5672"
        ports:
            - "5672:5672"
            - "15672:15672"