version: "2"

services:
    apigateway:
        build: ./Gateway/app/
        ports:
            - "5000"
        environment:
            - AZURE_SERVICE_BUS_NAMESPACE=dummynamespaceurl
            - AZURE_SERVICE_BUS_POLICY=dummypolicyname
            - AZURE_SERVICE_BUS_KEY=dummykey
            - AZURE_SERVICE_BUS_QUEUE=dummyqueuename
            - USERS_SERVICE=users
            - BIKES_SERVICE=bikes
        links:
            - bikes
            - users
        depends_on:
            - bikes
            - reservationengine
            - users

    devsite:
        build: ./DevSite/
        environment:
            - GATEWAY_SERVICE_URI=http://apigateway:5000
        links:
            - apigateway
        depends_on:
            - apigateway
        ports:
            - "8080:80"

    bikes:
        build: ./Bikes/
        environment:
            - MONGO_DB_CONNECTION_STRING=<insert connection string here>
            - MONGO_DB_COLLECTION=bikes
        ports:
            - "8081:80"

    reservationengine:
        build: ./ReservationEngine/app/
        environment:
            - AZURE_SERVICE_BUS_NAMESPACE=dummynamespaceurl
            - AZURE_SERVICE_BUS_POLICY=dummypolicyname
            - AZURE_SERVICE_BUS_KEY=dummykey
            - AZURE_SERVICE_BUS_QUEUE=dummyqueuename
            - BIKES_SERVICE=bikes
            - RESERVATION_MONGODB_CONNECTION_STRING=dummymongoconnection
            - RESERVATION_MONGODB_DATABASE=dummymongodb
            - RESERVATION_MONGODB_COLLECTION=dummymongocollection
        depends_on:
            - bikes
        links:
            - bikes

    users:
        build: ./Users/app/
        ports:
            - "8082:80"
        environment:
            - USER_SQLDB_USERNAME=dummyuser
            - USER_SQLDB_PASSWORD=dummypassword
            - USER_SQLDB_SERVER=dummydbserver
            - USER_SQLDB_DATABASE=dummydb