version: "2"

services:
    apigateway:
        build: ./Gateway/
        ports:
            - "5000:5000"
        environment:
            - AZURE_SERVICE_BUS_CONNECTIONSTRING=amqp://admin:admin@servicebus
            - AZURE_SERVICE_BUS_QUEUE=testqueue
            - NOTIFICATION_AMQP_CONNECTIONSTRING=amqp://rabbit
            - NOTIFICATION_OUT_EXCHANGE_NAME=out
            - USERS_SERVICE=users
            - BIKES_SERVICE=bikes
            - RESERVATIONS_SERVICE=reservations
            - BILLING_SERVICE=billing
            - APPLICATION_INSIGHTS_KEY=190c4eb0-6fb3-46b3-bb21-ec6be6523e49
        links:
            - bikes
            - users
            - billing
            - reservations
            - servicebus
        depends_on:
            - bikes
            - reservationengine
            - users
            - billing
            - reservations
            - servicebus

    devsite:
        build: ./DevSite/
        environment:
            - GATEWAY_SERVICE_URI=http://apigateway:5000
        links:
            - apigateway
        depends_on:
            - apigateway
        ports:
            - "8080:80"

    bikes:
        build: ./Bikes/
        environment:
            - MONGO_DB_CONNECTION_STRING=mongodb://mongo
            - MONGO_DB_COLLECTION=bikes
        depends_on:
            - mongo
        links:
            - mongo
        ports:
            - "8081:80"

    users:
        build: ./Users/
        ports:
            - "8082:80"
        environment:
            - USER_SQLDB_USERNAME=SA
            - USER_SQLDB_PASSWORD=!DummyPassword123!
            - USER_SQLDB_SERVER=sql
            - USER_SQLDB_DATABASE=tempdb
            - USER_SQLDB_TABLE=dummytable
        depends_on:
            - sql
        links:
            - sql

    billing:
        build: ./Billing/
        ports:
            - "8083:80"
        environment:
            - MONGODB_CONNECTION_STRING=mongodb://mongo
            - MONGODB_DBNAME=billing
        depends_on:
            - mongo
        links:
            - mongo

    reservations:
        build: ./Reservation/
        ports:
            - "8084:80"
        environment:
            - RESERVATION_MONGODB_CONNECTION_STRING=mongodb://mongo
            - RESERVATION_MONGODB_DATABASE=resdb
            - RESERVATION_MONGODB_COLLECTION=reservation
        depends_on:
            - mongo
        links:
            - mongo

    reservationengine:
        build: ./ReservationEngine/
        environment:
            - AZURE_SERVICE_BUS_CONNECTIONSTRING=amqp://admin:admin@servicebus
            - AZURE_SERVICE_BUS_QUEUE=testqueue
            - RESERVATION_MONGODB_CONNECTION_STRING=mongodb://mongo
            - RESERVATION_MONGODB_DATABASE=resdb
            - RESERVATION_MONGODB_COLLECTION=reservation
            - NOTIFICATION_AMQP_CONNECTIONSTRING=amqp://rabbit
            - NOTIFICATION_IN_EXCHANGE_NAME=in
            - NOTIFICATION_ROUTING_KEY=reservation
            - BIKES_SERVICE=bikes
            - BILLING_SERVICE=billing
        depends_on:
            - bikes
            - mongo
            - notification
            - billing
            - reservations
            - servicebus
        links:
            - bikes
            - mongo
            - reservations
            - billing
            - notification
            - servicebus

    notification:
        build: ./Notification/
        environment:
            - OUT_AMQP_CONNECTIONSTRING=amqp://rabbit
            - IN_AMQP_CONNECTIONSTRING=amqp://rabbit
            - OUT_EXCHANGE=out
            - IN_EXCHANGE=in
            - IN_BINDINGKEY=reservation
            - CONSUMERTAG_OVERRIDE=
        depends_on:
            - rabbit
        links:
            - rabbit

    mongo:
        image: mongo:3.4
        expose:
            - "27017"
        ports:
            - "27017:27017"

    rabbit:
        image: rabbitmq:3-management
        expose:
            - "5672"
        ports:
            - "5672:5672"
            - "15672:15672"  # WebUI

    servicebus:
        image: rmohr/activemq:5.14.3
        expose:
            - "5672"
        ports:
            - "8161:8161"  # WebUI
            - "56721:5672"

    sql:
        image: "microsoft/mssql-server-linux"
        expose:
            - "1433"
        environment:
            - SA_PASSWORD=!DummyPassword123!
            - ACCEPT_EULA=Y