# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

hostedSql:
  enabled: true
  password: "!DummyPassword123!"
hostedRabbit:
  enabled: true
hostedMongo:
  enabled: true
hostedServiceBus:
  enabled: true

contoso-bikerental-devsite:
  serviceType: LoadBalancer
  replicaCount: 2
  image:
    repository: stevenryregistry-microsoft.azurecr.io
    tag: latest
    pullPolicy: Always
    repoCredsSecretName: myregistrykey
  dependencies:
    gateway:
      dnsName: contoso-bikerental-gateway

contoso-bikerental-gateway:
  serviceType: ClusterIP
  replicaCount: 2
  image:
    repository: stevenryregistry-microsoft.azurecr.io
    tag: latest
    pullPolicy: Always
    repoCredsSecretName: myregistrykey
  dependencies:
    users:
      dnsName: contoso-bikerental-users
    bikes:
      dnsName: contoso-bikerental-bikes
    reservations:
      dnsName: contoso-bikerental-reservations
    billing:
      dnsName: contoso-bikerental-billing
    notification:
      connectionString: amqp://<>-contoso-bikerental-rabbit
      exchangeName: out
    serviceBus:
      connectionString: amqp://admin:admin@<>-contoso-bikerental-servicebus
      queue: testqueue
    applicationInsights:
      instrumentationKey: 00000000-0000-0000-0000-000000000000

contoso-bikerental-bikes:
  replicaCount: 2
  image:
    repository: stevenryregistry-microsoft.azurecr.io
    tag: latest
    pullPolicy: Always
    repoCredsSecretName: myregistrykey
  mongo:
    collection: bikes
    connectionString: mongodb://<>-contoso-bikerental-mongo

contoso-bikerental-reservationengine:
  replicaCount: 2
  image:
    repository: stevenryregistry-microsoft.azurecr.io
    tag: latest
    pullPolicy: Always
    repoCredsSecretName: myregistrykey
  dependencies:
    serviceBus:
      connectionString: amqp://admin:admin@<>-contoso-bikerental-servicebus
      queue: testqueue
    bikes:
      dnsName: contoso-bikerental-bikes
    billing:
      dnsName: contoso-bikerental-billing
    notification:
      connectionString: amqp://<>-contoso-bikerental-rabbit
      exchangeName: in
      routingKey: reservation
    mongo:
      connectionString: mongodb://<>-contoso-bikerental-mongo
      dbName: resdb
      collection: reservation

contoso-bikerental-users:
  replicaCount: 2
  image:
    repository: stevenryregistry-microsoft.azurecr.io
    tag: latest
    pullPolicy: Always
    repoCredsSecretName: myregistrykey
  dependencies:
    sql:
      username: SA
      password: "!DummyPassword123!"
      server: <>-contoso-bikerental-sql
      database: tempdb
      table: myTable

contoso-bikerental-reservations:
  replicaCount: 2
  image:
    repository: stevenryregistry-microsoft.azurecr.io
    tag: latest
    pullPolicy: Always
    repoCredsSecretName: myregistrykey
  mongo:
    connectionString: mongodb://<>-contoso-bikerental-mongo
    dbName: resdb
    collection: reservation

contoso-bikerental-billing:
  replicaCount: 2
  image:
    repository: stevenryregistry-microsoft.azurecr.io
    tag: latest
    pullPolicy: Always
    repoCredsSecretName: myregistrykey
  mongo:
    connectionString: mongodb://<>-contoso-bikerental-mongo
    dbName: billing

contoso-bikerental-notification:
  replicaCount: 2
  image:
    repository: stevenryregistry-microsoft.azurecr.io
    tag: latest
    pullPolicy: Always
    repoCredsSecretName: myregistrykey
  inAmqp:
    connectionString: amqp://<>-contoso-bikerental-rabbit
    exchangeName: in
    bindingKey: reservation
    consumerTagOverride:
  outAmqp:
    connectionString: amqp://<>-contoso-bikerental-rabbit
    exchangeName: out