# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

contoso-bikerental-gateway:
  serviceType: ClusterIP
  replicaCount: 1
  image:
    repository: stevenryregistry-microsoft.azurecr.io
    tag: latest
    pullPolicy: Always
    repoCredsSecretName: myregistrykey
  dependencies:
    users:
      dnsName: {{ .Release.Name }}-contoso-bikerental-users
    bikes:
      dnsName: {{ .Release.Name }}-contoso-bikerental-bikes
    serviceBus:
      namespace: dummynamespaceurl
      policy: dummypolicyname
      key: dummykey
      queue: dummyqueuename

contoso-bikerental-bikes:
  replicaCount: 1
  image:
    repository: stevenryregistry-microsoft.azurecr.io
    tag: latest
    pullPolicy: Always
    repoCredsSecretName: myregistrykey
  mongo:
    collection: bikes
    connectionString: <insert connection string here>

contoso-bikerental-reservationengine:
  replicaCount: 1
  image:
    repository: stevenryregistry-microsoft.azurecr.io
    tag: latest
    pullPolicy: Always
    repoCredsSecretName: myregistrykey
  dependencies:
    serviceBus:
      namespace: dummynamespaceurl
      policy: dummypolicyname
      key: dummykey
      queue: dummyqueuename
    bikes:
      dnsName: {{ .Release.Name }}-contoso-bikerental-bikes
    reservation:
      mongo:
        connectionString: dummymongoconnection
        collection: dummymongocollection
        database: dummymongodb

contoso-bikerental-users:
  replicaCount: 1
  image:
    repository: stevenryregistry-microsoft.azurecr.io
    tag: latest
    pullPolicy: Always
    repoCredsSecretName: myregistrykey
  dependencies:
    sql:
      username: dummyuser
      password: dummypassword
      server: dummyserver
      database: dummydatabase