{{- if .Values.hostedMongo.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-mongo
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-mongo
    spec:
      containers:
      - name: {{ .Chart.Name }}-mongo
        image: "mongo:3.4"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 27017
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
{{- end -}}