apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-rabbit
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: amqp
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: webui
  selector:
    app: {{ template "fullname" . }}-rabbit
