{{- if .Values.hostedServiceBus.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-servicebus
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-servicebus
    spec:
      containers:
      - name: {{ .Chart.Name }}-servicebus
        image: "rmohr/activemq:5.14.3"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5672
          - containerPort: 8161
        resources:
          limits:
            cpu: 100m
            memory: 3Gi
          requests:
            cpu: 100m
            memory: 3Gi
{{- end -}}