{{- if .Values.hostedSql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-sql
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  sql-password: {{ .Values.hostedSql.password | b64enc | quote }}
{{- end -}}